### ISSUE TITLE
Add "Connect with Paypal"-Button to Piggymetrics View

### ISSUE THREAD

**Issue by bajo1207** [bajo1207/piggymetrics#5]
Create a button in the UI that enables the user to log in with.
https://developer.paypal.com/docs/connect-with-paypal/

**Comment by jblossey** [comment]
**Please also think about #16 when adressing this issue.**

**Comment by jblossey** [comment]
Button callable (see PR #22 ). Yet to include html into piggymetrics view.

**Comment by jblossey** [comment]
Duplicate of newer issue #26

**Comment by jblossey** [comment]
This issue is worked on on branch [sign-in-button](https://github.com/bajo1207/piggymetrics/tree/joachimbachemathiesen/ch26/sign-in-button). Although as single application the gateway now displays the Paypal button. When launched with all other services it still only displays the text (at least on my local build).

**Comment by AndreasSpateneder** [comment]
Login button is now visible and completely integrated into the login page.
